#ifndef INSNS_H
#define INSNS_H

enum moxie_insn {
  moxie_i = 0,
  moxie_i_add_l,
  moxie_i_and,
  moxie_i_ashl,
  moxie_i_ashr,
  moxie_i_bad ,
  moxie_i_beq ,
  moxie_i_bge ,
  moxie_i_bgeu,
  moxie_i_bgt ,
  moxie_i_bgtu,
  moxie_i_ble ,
  moxie_i_bleu,
  moxie_i_blt,
  moxie_i_bltu,
  moxie_i_bne,
  moxie_i_brk,
  moxie_i_cmp,
  moxie_i_dec,
  moxie_i_div_l,
  moxie_i_gsr,
  moxie_i_inc,
  moxie_i_jmp,
  moxie_i_jmpa,
  moxie_i_jsr,
  moxie_i_jsra,
  moxie_i_ld_b,
  moxie_i_ld_l,
  moxie_i_ld_s,
  moxie_i_lda_b,
  moxie_i_lda_l,
  moxie_i_lda_s,
  moxie_i_ldi_b,
  moxie_i_ldi_l,
  moxie_i_ldi_s,
  moxie_i_ldo_b,
  moxie_i_ldo_l,
  moxie_i_ldo_s,
  moxie_i_lshr,
  moxie_i_mod_l,
  moxie_i_mov,
  moxie_i_mul_l,
  moxie_i_neg,
  moxie_i_nop,
  moxie_i_not,
  moxie_i_or,
  moxie_i_pop,
  moxie_i_push,
  moxie_i_ret,
  moxie_i_ssr,
  moxie_i_st_b,
  moxie_i_st_l,
  moxie_i_st_s,
  moxie_i_sta_b,
  moxie_i_sta_l,
  moxie_i_sta_s,
  moxie_i_sto_b,
  moxie_i_sto_l,
  moxie_i_sto_s,
  moxie_i_sub_l,
  moxie_i_swi,
  moxie_i_udiv_l,
  moxie_i_umod_l,
  moxie_i_xor,
  MOXIE_LAST_INSN};

extern const char *moxie_insn_names[];
extern const char *moxie_reg_names[];

#endif
